{% set name = "parsy" %}
{% set version = "2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/parsy-{{ version }}.tar.gz
  sha256: e943147644a8cf0d82d1bcb5c5867dd517495254cea3e3eb058b1e421cb7561f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - parsy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/python-parsy/parsy
  summary: easy-to-use parser combinators, for parsing in pure Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpcloud
    - gforsyth
